# Generated by Django 4.2 on 2025-07-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='button_text',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='paragraph',
            field=models.TextField(),
        ),
    ]
